//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public abstract class Aircraft
		{
				public Aircraft ()
				{
				
				}

				public int Size {
						get;
						private		set;
				}

				public int Cleanlyness {
						get;
						private		set;
				}

				public int Maintenance {
						get;
						private	set;
				}

				public int Fuel {
						get;
						private set;
				}

				public int TaxiTime {
						get;
						private set;
				}
		}
}

