//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public abstract class GameEvent
		{

				public GameEvent (Aircraft ac, int time, int runway)
				{
						this.Aircraft = ac;
						this.TimeUntil = time;
						this.Runway = runway;
				}

				public int TimeUntil {
						get;
						set;
				}

				public Aircraft Aircraft {
						get;
						set;
				}

				public int Runway {
						get;
						set;
				}

				public abstract void Spawn ();
		}
}

