//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

namespace AssemblyCSharp
{
		public abstract class GameEvent
		{

				public GameEvent (Aircraft ac, int time, int runway)
				{
						this.Aircraft = ac;
						this.TimeUntil = time;
						this.Runway = runway;
				}

				public int TimeUntil {
						get;
						set;
				}

				public Aircraft Aircraft {
						get;
						set;
				}

				public int Runway {
						get;
						set;
				}

				protected Vector3 SpawnPoint1 ()
				{
						return GameObject.FindGameObjectWithTag ("spawnpoint1").transform.position;

				}

				protected Vector3 SpawnPoint2 ()
				{
						return  GameObject.FindGameObjectWithTag ("spawnpoint2").transform.position;
				}

				protected Vector3 SpawnPoint3 ()
				{
						return GameObject.FindGameObjectWithTag ("spawnpoint3").transform.position;
				}

				protected Vector3 SpawnPoint4 ()
				{
						return GameObject.FindGameObjectWithTag ("spawnpoint4").transform.position;
				}

				protected Vector3 SpawnPoint5 ()
				{
						return SpawnPoint1 () + new Vector3 (0f, 0f, -4.5f);
				}

				protected Vector3 SpawnPoint6 ()
				{
						return SpawnPoint2 () + new Vector3 (0f, 0f, -4.5f);
				}

				protected Vector3 SpawnPoint7 ()
				{
						return SpawnPoint3 () + new Vector3 (0f, 0f, -4.5f);
				}

				protected Vector3 SpawnPoint8 ()
				{
						return SpawnPoint4 ();
				}

				public abstract void Spawn ();
		}
}

