//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public abstract class PersonCard : Card
		{

				public int MaintenanceSkill {
						get;
						set;
				}

				public int CleanSkill {
						get;
						set;
				}

				public int Tiredness {
						get;
						set;
				}

		}
}

