//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class Round
		{
				public Round (int roundNumber, int draws)
				{
			this.RoundNumber = roundNumber;
			this.Draws = draws;
				}

		public int RoundNumber {
						get;
						set;
		}
		public int Draws {
						get;
						set;
		}
		}
}

