//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace AssemblyCSharp
{
		public class WaterCard:EnchancementCard,FoodCard
		{
				public WaterCard ()
				{
				}

				public override double getProbability ()
				{
						return 0.01;
				}

				public override Card Clone ()
				{
						WaterCard rtVal = new WaterCard ();
						rtVal.CleanPlus = this.CleanPlus;
						rtVal.Duration = this.Duration;
						rtVal.MaintenancePlus = this.MaintenancePlus;
						rtVal.TirednessMinus = this.TirednessMinus;
						return rtVal;
				}

				public override string getName ()
				{
						return "WaterCard";
				}
		}
}

