//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18331
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace AssemblyCSharp
{
		public class WrenchUltraMega2002Card:EnchancementCard,ToolCard
		{
				public WrenchUltraMega2002Card ()
				{
						this.Duration = 6;
						this.MaintenancePlus = 1;
				}

				public override double getProbability ()
				{
						return (10 / 3 / 100.0);
				}

				public override Card Clone ()
				{
						WrenchUltraMega2002Card rtVal = new WrenchUltraMega2002Card ();
						rtVal.CleanPlus = this.CleanPlus;
						rtVal.Duration = this.Duration;
						rtVal.MaintenancePlus = this.MaintenancePlus;
						rtVal.TirednessMinus = this.TirednessMinus;
						return rtVal;
				}

				public override string getName ()
				{
						return "WrenchUltraMega2002Card";
				}
		}
}

